### ISSUE TITLE
Possible Bug - Cannot Reach API End Points on Clean Build

### ISSUE THREAD

**Issue by tkbdsi** [Th3Whit3Wolf/voyager#96]
@Th3Whit3Wolf 

I am having trouble getting the API end points to respond for me. 

E.g./api/vi/commands just replies with localhost didn't send any data.

When I attempt a clean build and then a manual db:reset once I have docker-compose up, I get the following error:
(note that I've blocked out the fullpath since this is a public repo and it would include my full name etc, the full path certainly doesn't start with ............)

```
......./voyager/backend/node_modules/@prisma/client/runtime/index.js:45629
        throw new PrismaClientKnownRequestError(message, e.code, this.client._clientVersion, e.meta);
              ^

PrismaClientKnownRequestError: 
Invalid `prisma.user.create()` invocation:


  Unique constraint failed on the fields: (`email`)
    at Object.request (.............../voyager/backend/node_modules/@prisma/client/runtime/index.js:45629:15)
    at async PrismaClient._request (........../voyager/backend/node_modules/@prisma/client/runtime/index.js:46456:18)
    at async insertRandomUser (file:///............/voyager/backend/src/db/seeds/users.js:221:17) {
  code: 'P2002',
  clientVersion: '3.13.0',
  meta: { target: [ 'email' ] }
}

Node.js v17.7.0
```

**Comment by Th3Whit3Wolf** [comment]
Try running `npm run db:seed`. The current method for generating users doesn't guarantee their email to be unique.

That should be fixed soon(ish) though.

**Comment by Th3Whit3Wolf** [comment]
Should be fixed now. Let me know if you have any issues and I will reopen this issue.
